name: CD Pipeline (Deploy to HF Spaces)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Скачиваем код из GitHub
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Скачиваем модель из DVC хранилища
      - name: Pull Model from DVC
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          pip install dvc dvc-s3
          dvc pull

      # 3. Отправляем код и модель на Hugging Face
      - name: Push to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USER: zarenui # Замените на свой логин!
          SPACE_NAME: iris-api-lugovskoy # Замените на имя спейса!
        run: |
          # Настраиваем Git
          git config --global user.email "bot@github.actions"
          git config --global user.name "GitHub CD Bot"
          
          # Клонируем пустой репозиторий из Hugging Face
          git clone https://$HF_USER:$HF_TOKEN@huggingface.co/spaces/$HF_USER/$SPACE_NAME space_repo
          
          # Копируем нужные файлы (включая скачанную модель) в папку спейса
          cp -r src/ space_repo/src/
          cp -r models/ space_repo/models/
          cp requirements.txt space_repo/requirements.txt
          cp Dockerfile space_repo/Dockerfile
          
          # ❗️ ЖЕЛЕЗОБЕТОННАЯ ОЧИСТКА МУСОРА:
          # Ищем и удаляем файлы mlflow.db и кэш __pycache__ во всех вложенных папках
          find space_repo -name "mlflow.db" -type f -delete
          find space_repo -name "__pycache__" -type d -exec rm -rf {} +
          
          # Пушим на сервер
          cd space_repo
          git add .
          git commit -m "Автоматический деплой из GitHub Actions" || echo "Изменений нет"
          git push